export default function Feedback(props) {
  console.log(props.isCorrect);
  let body = "Feedback: " + (props.isCorrect ? "That's right! " : "Look carefully! ");
  let classes = "card " + (props.isCorrect ? "green" : 'red');

  if (props.isScam) {
    body += " This looks like content generated by a bot."
  } else {
    body += " It is very hard for a bot to generate content like this."
  }

  return (
    <div className = {classes} >
      {body}
    </div>
  )
}